### ISSUE TITLE
Speaker Issue

### ISSUE THREAD

**Issue by Analytic-Playground** [mykle1/Hello-Lucy#25]
Hey, sorry Pi noobie here. 
I'm trying to get my speaker and microphone set up and keep getting the following error when trying to run speaker-test

> Write error: -77, File descriptor in bad state
> xrun_recovery failed: -77, File descriptor in bad state
> Transfer failed: File descriptor in bad state

I've been posting on some message boards and it looks like my pi might not have enough power to run my speaker?
I'm just looking for a tried and true speaker I can order that will work with my pi and Hello-Lucy(:

**Comment by mykle1** [comment]
Hmm, I don't know what to recommend to you. I developed Lucy on a laptop because the Pi just wasn't handling the load. I only run MagicMirror on laptop boards now. My only Pi mirror (the first) does not use Lucy at all. The response time was/is too slow for me. Good luck finding a speaker solution. Peace!
