### ISSUE TITLE
Good work with this

### ISSUE THREAD

**Issue by J0han3s** [mykle1/Hello-Lucy#28]
Very good work with this Mykle!

Any chance of creating a male face? so i can add a male voice?

any chance of sending notifications to Remote-Control module so we can use custom commands?

**Comment by mykle1** [comment]
Thanks for your king words.

You can create any face you like and create any sound file you like (male voice, alien, etc. 

Feel free to fork the module and make any changes you like. I don't have any plans to modify Lucy at this time.

I am closing this issue because it's a feature rewuest, not an issue.

Thanks for your interest
