### ISSUE TITLE
Improving sentences in MMM-voice.js replacement

### ISSUE THREAD

**Issue by E3V3A** [mykle1/Hello-Lucy#4]
Improving sentences in MMM-voice.js replacement. 

I propose to make the sentences found in MMM-voice.js (replacement) to be in their own file.
Perhaps as a list of the module names, since the `SHOW`, and `HIDE` prefix words are always the same for all. 

Then it's very easy to add for anyone...

BTW. @mykle1  a question:
* Why did you choose to replace MMM-voice, rather than ask him to incorporate your changes? 
 Reason I'm asking, it seem that in case he need to make changes in that module, I guess it can brake yours?

**Comment by mykle1** [comment]
That's a good proposition. However, I wouldn't know how to do that. :-/

I didn't ask him to incorporate my changes because I didn't think he would want them. He has helped me in the past and I appreciate everything that he has done for me. He is a genius. I'm just an old guy trying to have some fun. I didn't want to bother him with this. I think he would not even like what I've done so I saved him from having to say no if I asked him.
